#!/usr/bin/env python3

import sys,time, math
cin=sys.stdin
cerr=sys.stderr
cout=sys.stdout
#sys.setrecursionlimit(1e15)
def rl(cin):
	"""readline and remove \n"""
	return cin.readline()[:-1]
cin.rl=lambda:rl(cin)
def rs(cin):
	return cin.rl().split()
cin.rs=lambda:rs(cin)
def ri(cin):
	return int(cin.rl())
cin.ri=lambda:ri(cin)
def riv(cin):
	return [int(x) for x in rs(cin)]
cin.riv=lambda:riv(cin)
def rf(cin):
	return float(cin.rl())
cin.rf=lambda:rf(cin)
def rfv(cin):
	return [float(x) for x in rs(cin)]
cin.rfv=lambda:rfv(cin)
def rev(i):
	o=[]	
	for x in range(1,1+len(i)): o+=[i[-x]]
	return o
def revs(s):
	return ''.join(rev(s))	
def isPrime(n):
	for i in range(2, int(math.sqrt(n))):
		if not i%n:
			return true
		
def printr(*args):
	cerr.write(', '.join([repr(x) for x in args])+'\n')
		
class bin_base:
	def __init__(self):
		pass
	def up(self):
		pass
	def lo(self):
		pass
	def cont(self):
		pass
class bin_int:
	def __init__(self, m=0, M=10):
		self.m=m-1
		self.M=M+1
		self.c=int((self.M+self.m)/2)
	def up(self):
		self.m=self.c+1
		self.c=int((self.M+self.m)/2)
		return self.c
	def lo(self):
		self.M=self.c
		self.c=int((self.m+self.M)/2)
		return self.c
	def cont(self):
		return self.m < self.M

def search(r, k, pred):
	while r.cont():
		pre=pred(r.c)
		if pre < k:
			r.up()
		else:
			r.lo()
	return r.m

def step(u, v, ci, t, ce, cs, n, e, s, d, us = [], prev = -1):
	if ci == v: return t
	usc = list(us)
	# for each edge
	# keep horse or use current horse
	dist = 1e15
	for i in range(n):
		if d[ci][i] != -1:
			t1 = 1e15
			if e[ci] >= d[ci][i]:
				if not(ci in us or e[i] < ce and s[i] < cs):
					t1 = step(u,v, i, t + d[ci][i]/s[ci], e[ci] - d[ci][i], s[ci], n, e, s, d, list(us) + [ci], ci )
			t2 = 1e15
			if ce >= d[ci][i]:
				if i != prev:
					if not(e[i] >= ce and s[i] >= cs):
						t2 = step(u,v, i, t + d[ci][i]/cs, ce - d[ci][i], cs, n, e, s, d, us, ci )
			dist=min(t1,t2,dist)
	return dist

def do(l):
	n, q = l.riv()
	e = []
	s = []
	d = []
	uv = []
	for i in range(n):
		ei, si = l.riv()
		e += [float(ei)]
		s += [float(si)]
	for i in range(n):
		d += [[float(x) for x in l.riv()]] 
	for i in range(q):
		ui,vi = l.riv()
		uv += [(ui,vi)]
	
	r=[]
	for i in range(q):
		r += [step(uv[i][0]-1,uv[i][1]-1,uv[i][0]-1,0,0,1,n,e,s,d)]
	return ' '.join([str(x) for x in r])

def main():
	start = time.time()
	T=cin.ri()
	cerr.write("Going to process {} cases\n".format(T))
	k=0
	for Ti in range(1,T+1):
		if math.log(100*Ti/T) > k:
			cerr.write("case {}...".format(Ti))
		print("case #{0}: {1}".format(Ti, do(sys.stdin)))
		if math.log(100*Ti/T) > k:
			k+=1
			cerr.write("duration {}\n".format(time.time()-start))
	cerr.write("duration {0}\n".format(time.time()-start))

if __name__=="__main__":
	main()

